name: Minecraft Mod Build

on:
  workflow_dispatch: # Telefondan manuel basılacak butonu aktif eder

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project Codes
        uses: actions/checkout@v4

      - name: Setup Java 17 Runtime
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant Execute Permission for Gradle
        run: chmod +x gradlew

      - name: Run Gradle Build
        run: ./gradlew build

      - name: Upload Mod Jar Artifact
        uses: actions/artifacts@v4
        with:
          name: KaderiniSecMod-Jar
          path: build/libs/*.jar
          
