name: Minecraft Mod Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project Codes
        uses: actions/checkout@v4

      - name: Setup Java 17 Runtime
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Fix Missing Gradle Wrapper
        run: |
          echo "Eksik Gradle motoru kuruluyor..."
          mkdir -p gradle/wrapper
          # Resmi Gradle sunucusundan eksik olan wrapper jar dosyasını çeker
          curl -L -o gradle/wrapper/gradle-wrapper.jar https://raw.githubusercontent.com/gradle/gradle/v8.5.0/gradle/wrapper/gradle-wrapper.jar
          # Eşlik eden özellikler dosyasını oluşturur
          echo "distributionBase=GRADLE_USER_HOME" > gradle/wrapper/gradle-wrapper.properties
          echo "distributionPath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
          echo "distributionUrl=https\://services.gradle.org/distributions/gradle-8.5-bin.zip" >> gradle/wrapper/gradle-wrapper.properties
          echo "zipStoreBase=GRADLE_USER_HOME" >> gradle/wrapper/gradle-wrapper.properties
          echo "zipStorePath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties

      - name: Grant Execute Permission for Gradle
        run: chmod +x gradlew

      - name: Run Gradle Build
        run: ./gradlew build --no-daemon

      - name: Upload Mod Jar Artifact
        uses: actions/upload-artifact@v4
        with:
          name: KaderiniSecMod-Jar
          path: build/libs/*.jar
          
