name: Minecraft Mod Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project Codes
        uses: actions/checkout@v3

      - name: Setup Java 17 Runtime
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant Execute Permission for Gradle
        run: chmod +x gradlew

      - name: Run Gradle Build
        run: ./gradlew build --no-daemon

      - name: Upload Mod Jar Artifact
        uses: actions/upload-artifact@v3
        with:
          name: KaderiniSecMod-Jar
          path: build/libs/*.jar
          
